keyconfig_data = \
[("View2D",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("view2d.scroller_activate", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroller_activate", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("view2d.pan", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("view2d.pan", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view2d.pan", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view2d.scroll_right", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view2d.scroll_left", {"type": 'WHEELUPMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view2d.scroll_down", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view2d.scroll_up", {"type": 'WHEELUPMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view2d.ndof", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("view2d.zoom_out", {"type": 'WHEELOUTMOUSE', "value": 'PRESS'}, None),
    ("view2d.zoom_in", {"type": 'WHEELINMOUSE', "value": 'PRESS'}, None),
    ("view2d.zoom_out", {"type": 'NUMPAD_MINUS', "value": 'PRESS'}, None),
    ("view2d.zoom_in", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("view2d.zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("view2d.smoothview", {"type": 'TIMER1', "value": 'ANY', "any": True}, None),
    ("view2d.scroll_down", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_up", {"type": 'WHEELUPMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_right", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_left", {"type": 'WHEELUPMOUSE', "value": 'PRESS'}, None),
    ("view2d.zoom", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("view2d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view2d.zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ("3D View",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("view3d.cursor3d", {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True}, None),
    ("view3d.localview", {"type": 'NUMPAD_SLASH', "value": 'PRESS'}, None),
    ("view3d.localview", {"type": 'SLASH', "value": 'PRESS'}, None),
    ("view3d.localview_remove_from", {"type": 'M', "value": 'PRESS'}, None),
    ("view3d.rotate", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("view3d.move", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view3d.zoom", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "oskey": True}, None),
    ("view3d.dolly", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ],
      },
     ),
    ("view3d.view_selected",
     {"type": 'COMMA', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.smoothview", {"type": 'TIMER1', "value": 'ANY', "any": True}, None),
    ("view3d.rotate", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view3d.rotate", {"type": 'MOUSEROTATE', "value": 'ANY'}, None),
    ("view3d.move", {"type": 'TRACKPADPAN', "value": 'ANY', "shift": True}, None),
    ("view3d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view3d.zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("view3d.zoom",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELINMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELOUTMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'EQUAL', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'MINUS', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.view_center_camera", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_center_lock", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS'},
     {"properties":
      [("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("center", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_view_pie'),
       ],
      },
     ),
    ("view3d.navigate", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "shift": True}, None),
    ("view3d.view_camera", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITDOWN'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_4', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITLEFT'),
       ],
      },
     ),
    ("view3d.view_persportho", {"type": 'NUMPAD_5', "value": 'PRESS'}, None),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_6', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_8', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITUP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANDOWN'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANLEFT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_6', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANRIGHT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANUP'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_6', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_9', "value": 'PRESS'},
     {"properties":
      [("angle", 3.1415927),
       ("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'NORTH', "alt": True},
     {"properties":
      [("type", 'TOP'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'SOUTH', "alt": True},
     {"properties":
      [("type", 'BOTTOM'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'EAST', "alt": True},
     {"properties":
      [("type", 'RIGHT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'WEST', "alt": True},
     {"properties":
      [("type", 'LEFT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_center_pick", {"type": 'MIDDLEMOUSE', "value": 'CLICK', "alt": True}, None),
    ("view3d.ndof_orbit_zoom", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("view3d.ndof_orbit", {"type": 'NDOF_MOTION', "value": 'ANY', "ctrl": True}, None),
    ("view3d.ndof_pan", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True}, None),
    ("view3d.ndof_all", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BACK', "value": 'PRESS'},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_LEFT', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BOTTOM', "value": 'PRESS'},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("center", True),
       ("object", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("toggle", True),
       ("center", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("view3d.select_lasso",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("view3d.select_lasso",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("view3d.clip_border", {"type": 'B', "value": 'PRESS', "alt": True}, None),
    ("view3d.zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("view3d.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.camera_to_view", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.object_as_camera", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.copybuffer", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.pastebuffer", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'EVT_TWEAK_R', "value": 'ANY'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.bend", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_PT_snapping'),
       ("keep_open", False),
       ],
      },
     ),
    ("object.transform_axis_target", {"type": 'T', "value": 'PRESS', "shift": True}, None),
    ("transform.skin_resize", {"type": 'A', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_snap_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_gizmo'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_pivot_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'COMMA', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_orientations_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Z', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_shading_pie'),
       ],
      },
     ),
    ("view3d.toggle_shading",
     {"type": 'Z', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'WIREFRAME'),
       ],
      },
     ),
    ("view3d.toggle_xray", {"type": 'Z', "value": 'PRESS', "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ],
   },
  ),
 ("Node Editor",
  {"space_type": 'NODE_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'NODE_MT_nw_switch_node_type_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'NODE_MT_nw_copy_node_properties_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'BACK_SLASH', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_nw_link_active_to_selected_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'NUMPAD_SLASH', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_nw_add_reroutes_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'SLASH', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_nw_add_reroutes_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'NODE_MT_nw_node_wrangler_menu'),
       ],
      },
     ),
    ("node.nw_reset_nodes", {"type": 'BACK_SPACE', "value": 'PRESS'}, None),
    ("node.nw_align_nodes", {"type": 'EQUAL', "value": 'PRESS', "shift": True}, None),
    ("node.nw_viewer_focus", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'}, None),
    ("node.nw_lazy_connect",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("with_menu", True),
       ],
      },
     ),
    ("node.nw_lazy_connect",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("with_menu", False),
       ],
      },
     ),
    ("node.nw_lazy_mix", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("node.nw_reload_images", {"type": 'R', "value": 'PRESS', "alt": True}, None),
    ("node.nw_emission_viewer", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("node.nw_swap_links", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("node.nw_frame_selected", {"type": 'P', "value": 'PRESS', "shift": True}, None),
    ("node.nw_del_unused", {"type": 'X', "value": 'PRESS', "alt": True}, None),
    ("node.nw_bg_reset", {"type": 'Z', "value": 'PRESS'}, None),
    ("node.nw_add_textures_for_principled", {"type": 'T', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("node.nw_add_texture", {"type": 'T', "value": 'PRESS', "ctrl": True}, None),
    ("node.nw_select_parent_child",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("option", 'PARENT'),
       ],
      },
     ),
    ("node.nw_select_parent_child",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("option", 'CHILD'),
       ],
      },
     ),
    ("node.nw_link_out", {"type": 'O', "value": 'PRESS'}, None),
    ("node.nw_detach_outputs", {"type": 'D', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("node.nw_copy_label",
     {"type": 'V', "value": 'PRESS', "shift": True},
     {"properties":
      [("option", 'FROM_ACTIVE'),
       ],
      },
     ),
    ("node.nw_modify_labels", {"type": 'L', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("node.nw_clear_label",
     {"type": 'L', "value": 'PRESS', "alt": True},
     {"properties":
      [("option", False),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("option", 1.0),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("option", 1.0),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'ZERO', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("option", 0.0),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'NUMPAD_0', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("option", 0.0),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("option", 1.0),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("option", 0.0),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("option", 0.01),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("option", -0.01),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "alt": True},
     {"properties":
      [("option", 0.1),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "alt": True},
     {"properties":
      [("option", -0.1),
       ],
      },
     ),
    ("node.nw_link_active_to_selected",
     {"type": 'SEMI_COLON', "value": 'PRESS', "shift": True},
     {"properties":
      [("replace", True),
       ("use_node_name", False),
       ("use_outputs_names", True),
       ],
      },
     ),
    ("node.nw_link_active_to_selected",
     {"type": 'SEMI_COLON', "value": 'PRESS'},
     {"properties":
      [("replace", False),
       ("use_node_name", False),
       ("use_outputs_names", True),
       ],
      },
     ),
    ("node.nw_link_active_to_selected",
     {"type": 'QUOTE', "value": 'PRESS', "shift": True},
     {"properties":
      [("replace", True),
       ("use_node_name", True),
       ("use_outputs_names", False),
       ],
      },
     ),
    ("node.nw_link_active_to_selected",
     {"type": 'QUOTE', "value": 'PRESS'},
     {"properties":
      [("replace", False),
       ("use_node_name", True),
       ("use_outputs_names", False),
       ],
      },
     ),
    ("node.nw_link_active_to_selected",
     {"type": 'K', "value": 'PRESS', "shift": True},
     {"properties":
      [("replace", True),
       ("use_node_name", False),
       ("use_outputs_names", False),
       ],
      },
     ),
    ("node.nw_link_active_to_selected",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("replace", False),
       ("use_node_name", False),
       ("use_outputs_names", False),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'UP_ARROW', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'PREV'),
       ("operation", 'PREV'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'NEXT'),
       ("operation", 'NEXT'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'PERIOD', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'CURRENT'),
       ("operation", 'GREATER_THAN'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'COMMA', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'CURRENT'),
       ("operation", 'LESS_THAN'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'SLASH', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'DIVIDE'),
       ("operation", 'DIVIDE'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'NUMPAD_SLASH', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'DIVIDE'),
       ("operation", 'DIVIDE'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'MINUS', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'SUBTRACT'),
       ("operation", 'SUBTRACT'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'SUBTRACT'),
       ("operation", 'SUBTRACT'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'EIGHT', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'MULTIPLY'),
       ("operation", 'MULTIPLY'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'MULTIPLY'),
       ("operation", 'MULTIPLY'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'EQUAL', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'ADD'),
       ("operation", 'ADD'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'ADD'),
       ("operation", 'ADD'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'ZERO', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'MIX'),
       ("operation", 'CURRENT'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'NUMPAD_0', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'MIX'),
       ("operation", 'CURRENT'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'PERIOD', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'GREATER_THAN'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'COMMA', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'LESS_THAN'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'SLASH', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'DIVIDE'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_SLASH', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'DIVIDE'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'MINUS', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUBTRACT'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUBTRACT'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'EIGHT', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'MULTIPLY'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'MULTIPLY'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'EQUAL', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'SLASH', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'DIVIDE'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_SLASH', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'DIVIDE'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUBTRACT'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUBTRACT'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'EIGHT', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'MULTIPLY'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'MULTIPLY'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'MIX'),
       ("merge_type", 'ALPHAOVER'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'MIX'),
       ("merge_type", 'ALPHAOVER'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'MIX'),
       ("merge_type", 'ZCOMBINE'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'GREATER_THAN'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'COMMA', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'LESS_THAN'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'SLASH', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'DIVIDE'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_SLASH', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'DIVIDE'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'SUBTRACT'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'SUBTRACT'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'EIGHT', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'MULTIPLY'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'MULTIPLY'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'MIX'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'MIX'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("extend", False),
       ("deselect_all", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("extend", False),
       ("deselect_all", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select_box",
     {"type": 'EVT_TWEAK_R', "value": 'ANY'},
     {"properties":
      [("tweak", True),
       ],
      },
     ),
    ("node.select_lasso",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("node.select_lasso",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("node.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("node.link",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("detach", False),
       ],
      },
     ),
    ("node.link",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "ctrl": True},
     {"properties":
      [("detach", True),
       ],
      },
     ),
    ("node.resize", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("node.add_reroute", {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True}, None),
    ("node.links_cut", {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True}, None),
    ("node.select_link_viewer", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("node.backimage_move", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "alt": True}, None),
    ("node.backimage_zoom",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("factor", 0.8333333),
       ],
      },
     ),
    ("node.backimage_zoom",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("factor", 1.2),
       ],
      },
     ),
    ("node.backimage_fit", {"type": 'HOME', "value": 'PRESS', "alt": True}, None),
    ("node.backimage_sample", {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_context_menu'),
       ],
      },
     ),
    ("node.link_make",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("replace", False),
       ],
      },
     ),
    ("node.link_make",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("replace", True),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'NODE_MT_add'),
       ],
      },
     ),
    ("node.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("node.duplicate_move_keep_inputs", {"type": 'D', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("node.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("node.detach", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("node.join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("node.hide_toggle", {"type": 'H', "value": 'PRESS'}, None),
    ("node.mute_toggle", {"type": 'M', "value": 'PRESS'}, None),
    ("node.preview_toggle", {"type": 'H', "value": 'PRESS', "shift": True}, None),
    ("node.hide_socket_toggle", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("node.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("node.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("node.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("node.select_box",
     {"type": 'B', "value": 'PRESS'},
     {"properties":
      [("tweak", False),
       ],
      },
     ),
    ("node.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("node.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("node.delete_reconnect", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("node.delete_reconnect", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("node.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("node.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("node.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("node.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("node.select_linked_to", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("node.select_linked_from", {"type": 'L', "value": 'PRESS'}, None),
    ("node.select_grouped",
     {"type": 'G', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select_grouped",
     {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select_same_type_step",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("prev", False),
       ],
      },
     ),
    ("node.select_same_type_step",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("prev", True),
       ],
      },
     ),
    ("node.find_node", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("node.group_make", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("node.group_ungroup", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("node.group_separate", {"type": 'P', "value": 'PRESS'}, None),
    ("node.group_edit",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("exit", False),
       ],
      },
     ),
    ("node.group_edit",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("exit", True),
       ],
      },
     ),
    ("node.read_viewlayers", {"type": 'R', "value": 'PRESS', "ctrl": True}, None),
    ("node.render_changed", {"type": 'Z', "value": 'PRESS'}, None),
    ("node.clipboard_copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("node.clipboard_paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("node.viewer_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("node.clear_viewer_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("node.translate_attach", {"type": 'G', "value": 'PRESS'}, None),
    ("node.translate_attach", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("node.translate_attach", {"type": 'EVT_TWEAK_R', "value": 'ANY'}, None),
    ("transform.translate",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("release_confirm", True),
       ],
      },
     ),
    ("transform.translate",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("release_confirm", True),
       ],
      },
     ),
    ("transform.translate",
     {"type": 'EVT_TWEAK_R', "value": 'ANY'},
     {"properties":
      [("release_confirm", True),
       ],
      },
     ),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("node.move_detach_links", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("node.move_detach_links_release", {"type": 'EVT_TWEAK_L', "value": 'ANY', "alt": True}, None),
    ("node.move_detach_links", {"type": 'EVT_TWEAK_R', "value": 'ANY', "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("data_path", 'tool_settings.snap_node_element'),
       ],
      },
     ),
    ("node.eswc_switch_back_to_timeline", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("node.eswc_switch_to_composite_nodepanel", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ("File Browser Main",
  {"space_type": 'FILE_BROWSER', "region_type": 'WINDOW'},
  {"items":
   [("file.execute",
     {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("need_active", True),
       ],
    "active":False,
      },
     ),
    ("file.refresh", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("file.select", {"type": 'LEFTMOUSE', "value": 'CLICK'}, None),
    ("file.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("file.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.select",
     {"type": 'RIGHTMOUSE', "value": 'CLICK'},
     {"properties":
      [("open", False),
       ],
      },
     ),
    ("file.select",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("open", False),
       ],
    "active":False,
      },
     ),
    ("file.select",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("extend", True),
       ("fill", True),
       ("open", False),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS'},
     {"properties":
      [("direction", 'UP'),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'UP'),
       ("extend", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("direction", 'UP'),
       ("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS'},
     {"properties":
      [("direction", 'DOWN'),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'DOWN'),
       ("extend", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("direction", 'DOWN'),
       ("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS'},
     {"properties":
      [("direction", 'LEFT'),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'LEFT'),
       ("extend", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("direction", 'LEFT'),
       ("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS'},
     {"properties":
      [("direction", 'RIGHT'),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'RIGHT'),
       ("extend", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("direction", 'RIGHT'),
       ("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.previous", {"type": 'BUTTON4MOUSE', "value": 'CLICK'}, None),
    ("file.next", {"type": 'BUTTON5MOUSE', "value": 'CLICK'}, None),
    ("file.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("file.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("file.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("file.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("file.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("file.select_box", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("file.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("file.rename", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("file.highlight", {"type": 'MOUSEMOVE', "value": 'ANY', "any": True}, None),
    ("file.filenum",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS'},
     {"properties":
      [("increment", 1),
       ],
      },
     ),
    ("file.filenum",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("increment", 10),
       ],
      },
     ),
    ("file.filenum",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("increment", 100),
       ],
      },
     ),
    ("file.filenum",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS'},
     {"properties":
      [("increment", -1),
       ],
      },
     ),
    ("file.filenum",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("increment", -10),
       ],
      },
     ),
    ("file.filenum",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("increment", -100),
       ],
      },
     ),
    ("moviemanager_edit_range", {"type": 'E', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("Sequencer",
  {"space_type": 'SEQUENCE_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("sequencer.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("sequencer.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("sequencer.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("sequencer.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("sequencer.cut",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("type", 'SOFT'),
       ],
      },
     ),
    ("sequencer.cut",
     {"type": 'K', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'HARD'),
       ],
      },
     ),
    ("sequencer.mute",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("sequencer.mute",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("sequencer.unmute",
     {"type": 'H', "value": 'PRESS', "alt": True},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("sequencer.unmute",
     {"type": 'H', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("sequencer.lock", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("sequencer.unlock", {"type": 'L', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("sequencer.reassign_inputs", {"type": 'R', "value": 'PRESS'}, None),
    ("sequencer.reload", {"type": 'R', "value": 'PRESS', "alt": True}, None),
    ("sequencer.reload",
     {"type": 'R', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("adjust_length", True),
       ],
      },
     ),
    ("sequencer.refresh_all", {"type": 'R', "value": 'PRESS', "ctrl": True}, None),
    ("sequencer.offset_clear", {"type": 'O', "value": 'PRESS', "alt": True}, None),
    ("sequencer.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("sequencer.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("sequencer.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("sequencer.copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("sequencer.paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("sequencer.images_separate", {"type": 'Y', "value": 'PRESS'}, None),
    ("sequencer.meta_toggle", {"type": 'TAB', "value": 'PRESS'}, None),
    ("sequencer.meta_make", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("sequencer.meta_separate", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("sequencer.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("sequencer.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("sequencer.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("sequencer.view_frame", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("sequencer.strip_jump",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("next", True),
       ("center", False),
       ],
      },
     ),
    ("sequencer.strip_jump",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("next", False),
       ("center", False),
       ],
      },
     ),
    ("sequencer.strip_jump",
     {"type": 'PAGE_UP', "value": 'PRESS', "alt": True},
     {"properties":
      [("next", True),
       ("center", True),
       ],
      },
     ),
    ("sequencer.strip_jump",
     {"type": 'PAGE_DOWN', "value": 'PRESS', "alt": True},
     {"properties":
      [("next", False),
       ("center", True),
       ],
      },
     ),
    ("sequencer.swap",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "alt": True},
     {"properties":
      [("side", 'LEFT'),
       ],
      },
     ),
    ("sequencer.swap",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "alt": True},
     {"properties":
      [("side", 'RIGHT'),
       ],
      },
     ),
    ("sequencer.gap_remove",
     {"type": 'BACK_SPACE', "value": 'PRESS'},
     {"properties":
      [("all", False),
       ],
      },
     ),
    ("sequencer.gap_remove",
     {"type": 'BACK_SPACE', "value": 'PRESS', "shift": True},
     {"properties":
      [("all", True),
       ],
      },
     ),
    ("sequencer.gap_insert", {"type": 'EQUAL', "value": 'PRESS', "shift": True}, None),
    ("sequencer.snap", {"type": 'S', "value": 'PRESS', "shift": True}, None),
    ("sequencer.swap_inputs", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("sequencer.cut_multicam",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("camera", 1),
       ],
      },
     ),
    ("sequencer.cut_multicam",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("camera", 2),
       ],
      },
     ),
    ("sequencer.cut_multicam",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("camera", 3),
       ],
      },
     ),
    ("sequencer.cut_multicam",
     {"type": 'FOUR', "value": 'PRESS'},
     {"properties":
      [("camera", 4),
       ],
      },
     ),
    ("sequencer.cut_multicam",
     {"type": 'FIVE', "value": 'PRESS'},
     {"properties":
      [("camera", 5),
       ],
      },
     ),
    ("sequencer.cut_multicam",
     {"type": 'SIX', "value": 'PRESS'},
     {"properties":
      [("camera", 6),
       ],
      },
     ),
    ("sequencer.cut_multicam",
     {"type": 'SEVEN', "value": 'PRESS'},
     {"properties":
      [("camera", 7),
       ],
      },
     ),
    ("sequencer.cut_multicam",
     {"type": 'EIGHT', "value": 'PRESS'},
     {"properties":
      [("camera", 8),
       ],
      },
     ),
    ("sequencer.cut_multicam",
     {"type": 'NINE', "value": 'PRESS'},
     {"properties":
      [("camera", 9),
       ],
      },
     ),
    ("sequencer.cut_multicam",
     {"type": 'ZERO', "value": 'PRESS'},
     {"properties":
      [("camera", 10),
       ],
      },
     ),
    ("sequencer.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("extend", False),
       ("deselect_all", True),
       ("linked_handle", False),
       ("left_right", 'NONE'),
       ("linked_time", False),
       ],
      },
     ),
    ("sequencer.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ("linked_handle", False),
       ("left_right", 'NONE'),
       ("linked_time", False),
       ],
      },
     ),
    ("sequencer.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("extend", False),
       ("linked_handle", True),
       ("left_right", 'NONE'),
       ("linked_time", False),
       ],
      },
     ),
    ("sequencer.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ("linked_handle", True),
       ("left_right", 'NONE'),
       ("linked_time", False),
       ],
      },
     ),
    ("sequencer.select",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("extend", False),
       ("linked_handle", False),
       ("left_right", 'MOUSE'),
       ("linked_time", True),
       ],
      },
     ),
    ("sequencer.select",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("linked_handle", False),
       ("left_right", 'MOUSE'),
       ("linked_time", True),
       ],
      },
     ),
    ("sequencer.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("sequencer.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("sequencer.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("sequencer.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("sequencer.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("sequencer.select_box",
     {"type": 'EVT_TWEAK_R', "value": 'ANY'},
     {"properties":
      [("mode", 'SET'),
       ("tweak", True),
       ],
      },
     ),
    ("sequencer.select_box",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True},
     {"properties":
      [("mode", 'ADD'),
       ("tweak", True),
       ],
      },
     ),
    ("sequencer.select_box",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ("tweak", True),
       ],
      },
     ),
    ("sequencer.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("sequencer.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'SEQUENCER_MT_add'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'C', "value": 'PRESS'},
     {"properties":
      [("name", 'SEQUENCER_MT_change'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'SEQUENCER_MT_context_menu'),
       ],
      },
     ),
    ("sequencer.slip", {"type": 'S', "value": 'PRESS'}, None),
    ("wm.context_set_int",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'scene.sequence_editor.overlay_frame'),
       ("value", 0),
       ],
      },
     ),
    ("transform.seq_slide", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.seq_slide", {"type": 'EVT_TWEAK_R', "value": 'ANY'}, None),
    ("transform.transform",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_EXTEND'),
       ],
      },
     ),
    ("marker.add", {"type": 'M', "value": 'PRESS'}, None),
    ("marker.rename", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("moviemanager_insert_strip_masterscene", {"type": 'I', "value": 'PRESS'}, None),
    ("trimtools_trim_left", {"type": 'Q', "value": 'PRESS', "shift": True}, None),
    ("trimtools_trim_right", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("moviemanager_switch_back_to_timeline", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("sequencer.strip_jump",
     {"type": 'Q', "value": 'PRESS', "alt": True},
     {"properties":
      [("next", False),
       ("center", False),
       ],
      },
     ),
    ("sequencer.strip_jump",
     {"type": 'W', "value": 'PRESS', "alt": True},
     {"properties":
      [("center", False),
       ],
      },
     ),
    ("sequencer.eswc_switch_to_composite", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("sequencer.eswc_single_comp", {"type": 'C', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    import os
    from bl_keymap_utils.io import keyconfig_import_from_data
    keyconfig_import_from_data(os.path.splitext(os.path.basename(__file__))[0], keyconfig_data)
